version: '3.7'

services:
  db:
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file: db_secrets.env
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: nextcloud
    image: mariadb:10
    restart: always
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:5
    restart: always

  app:
    depends_on:
      - db
      - redis
    env_file: app_secrets.env
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_HOST: db
      MYSQL_USER: nextcloud
      NEXTCLOUD_ADMIN_USER: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: 'dmz.yong-ju.me'
      REDIS_HOST: redis
    image: nextcloud:17-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/media:/mnt/media

  web:
    build: ./web
    depends_on:
      - app
    environment:
      VIRTUAL_HOST: dmz.yong-ju.me
      LETSENCRYPT_HOST: dmz.yong-ju.me
      LETSENCRYPT_EMAIL: sei40kr@gmail.com
    networks:
      - proxy-tier
      - default
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro

  proxy:
    build: ./proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
    networks:
      - proxy-tier
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d

  letsencrypt-companion:
    depends_on:
      - proxy
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - proxy-tier
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
