version: '3.7'

services:

  prometheus:
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter
      - cadvisor
    image: prom/prometheus:v2.15.2
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:v0.18.1
    restart: always

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.35.0
    privileged: true
    restart: always
    volumes:
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run:/var/run:rw

  grafana:
    depends_on:
      - prometheus
    env_file: grafana_secrets.env
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana:/var/lib/grafana


volumes:
  grafana:
