. "${HOME}/.zplugin/bin/zplugin.zsh"

setopt APPEND_HISTORY
setopt AUTO_CD
setopt AUTO_LIST
setopt AUTO_MENU
setopt AUTO_PUSHD
setopt AUTO_PARAM_KEYS
setopt AUTO_PARAM_SLASH
setopt AUTO_RESUME
setopt EQUALS
setopt EXTENDED_HISTORY
setopt GLOB_DOTS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt INTERACTIVE_COMMENTS
setopt NO_BEEP
setopt NUMERIC_GLOB_SORT
setopt PRINT_EIGHT_BIT
setopt PROMPT_SUBST
setopt PUSHD_IGNORE_DUPS
setopt SHARE_HISTORY
unsetopt LIST_BEEP

bindkey -e

autoload -Uz _zplugin
if [[ "${+_comps}" == 1 ]]; then
    _comps[zplugin]=_zplugin
fi

zplugin snippet OMZ::lib/completion.zsh

zplugin ice wait'0' atinit'zpcompinit; zpcdreplay' lucid
zplugin light zdharma/fast-syntax-highlighting

zplugin ice wait'0' lucid
zplugin light -b zsh-users/zsh-autosuggestions

zplugin ice wait'0' lucid
zplugin light -b zdharma/history-search-multi-word

zplugin ice trackbinds
zplugin snippet OMZ::plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh

zplugin snippet OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh

zplugin ice aliases
zplugin snippet OMZ::plugins/archlinux/archlinux.plugin.zsh

zplugin ice pick'' blockf wait''
zplugin light zsh-users/zsh-completions

if [[ "$TERM" != dumb ]]; then
    zplugin snippet OMZ::lib/git.zsh
    zplugin snippet OMZ::lib/theme-and-appearance.zsh

    zplugin ice wait'!0' lucid
    zplugin snippet OMZ::themes/fishy.zsh-theme
fi
